//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoMySql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class avtor
    {
        public int id_avtor { get; set; }
        public string fam_io { get; set; }
        public string id_man { get; set; }
        public Nullable<int> kod1 { get; set; }
        public string data_change { get; set; }
    }
}
