//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoMySql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int id_book { get; set; }
        public string name_book { get; set; }
        public string kod_vid { get; set; }
        public string kod_grif { get; set; }
        public Nullable<int> kod_izdat { get; set; }
        public string year_create { get; set; }
        public Nullable<int> kolvo_str { get; set; }
        public Nullable<int> kolvo_vsego { get; set; }
        public string UDK { get; set; }
        public int id_kafedra { get; set; }
        public Nullable<int> ostatok { get; set; }
        public string kod1 { get; set; }
        public string data_change { get; set; }
    }
}
