//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoMySql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public int id_group { get; set; }
        public string year_postup { get; set; }
        public string name_group { get; set; }
        public string form { get; set; }
        public string kurator { get; set; }
        public string starosta { get; set; }
        public Nullable<int> kolvo_studentov { get; set; }
        public Nullable<int> id_specialistic { get; set; }
        public Nullable<int> vipusk { get; set; }
        public string kod1 { get; set; }
        public string data_change { get; set; }
        public string year_okonchan { get; set; }
    }
}
