//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoMySql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialistic
    {
        public int id_spec { get; set; }
        public string name_spec { get; set; }
        public string name_spec_kratko { get; set; }
        public Nullable<int> GOS_nomer { get; set; }
        public string kvalifikaciya { get; set; }
        public string napravlenie { get; set; }
        public Nullable<int> kod_kafedri { get; set; }
        public string GOS_disciplin { get; set; }
        public Nullable<int> kon_ekz_och { get; set; }
        public Nullable<int> kon_ekz_oz { get; set; }
        public Nullable<int> ekz_och { get; set; }
        public Nullable<int> ekz_oz { get; set; }
        public Nullable<int> kon_zach_och { get; set; }
        public Nullable<int> kon_zach_oz { get; set; }
        public Nullable<int> zach_och { get; set; }
        public Nullable<int> zach_oz { get; set; }
        public Nullable<int> gek { get; set; }
        public Nullable<int> gak { get; set; }
        public Nullable<int> rukvo_dip { get; set; }
        public Nullable<int> spec { get; set; }
        public Nullable<int> ekon { get; set; }
        public Nullable<int> bjd { get; set; }
        public Nullable<int> kkr_och { get; set; }
        public Nullable<int> kkp_och { get; set; }
        public Nullable<int> kkr_oz { get; set; }
        public Nullable<int> kkp_oz { get; set; }
    }
}
