//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoMySql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public int id_man { get; set; }
        public int kod_zvaniya { get; set; }
        public int kod_stepeni { get; set; }
        public string kvalifikaciya { get; set; }
        public string pedagog_staj { get; set; }
        public string nauch_pedagog_staj { get; set; }
    }
}
