//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoMySql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class variant
    {
        public int id_variant { get; set; }
        public Nullable<int> id_zadanie { get; set; }
        public Nullable<int> id_man { get; set; }
        public Nullable<int> variant1 { get; set; }
        public Nullable<float> ocenka { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public Nullable<float> answer { get; set; }
    }
}
