//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoMySql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vidacha
    {
        public int id_vid { get; set; }
        public string id_man { get; set; }
        public Nullable<int> id_book { get; set; }
        public string data_vidachi { get; set; }
        public string data_vozvrata { get; set; }
        public string na_rukah { get; set; }
        public string poterya { get; set; }
        public string primechanie { get; set; }
        public string kod1 { get; set; }
        public string data_change { get; set; }
    }
}
