//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoMySql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zadanie
    {
        public int id_zadanie { get; set; }
        public Nullable<int> id_vedet { get; set; }
        public string text { get; set; }
        public string fileref { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> srok { get; set; }
        public Nullable<sbyte> gpss { get; set; }
    }
}
