//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_v1._0._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int id_man { get; set; }
        public string fam { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public string INN { get; set; }
        public string sv_vo_PFR { get; set; }
        public string serial_pasport { get; set; }
        public string number_pasport { get; set; }
        public string data_vidachi_pasporta { get; set; }
        public string kem_vidan { get; set; }
        public string data_rojdeniya { get; set; }
        public string strana_1 { get; set; }
        public string region_1 { get; set; }
        public string index_1 { get; set; }
        public string gorod_1 { get; set; }
        public string ulica_1 { get; set; }
        public string dom_1 { get; set; }
        public string kv_1 { get; set; }
        public string strana_2 { get; set; }
        public string region_2 { get; set; }
        public string index_2 { get; set; }
        public string gorod_2 { get; set; }
        public string ulica_2 { get; set; }
        public string dom_2 { get; set; }
        public string kv_2 { get; set; }
        public string telefon_dom { get; set; }
        public string telefon_sot { get; set; }
        public string e_mail { get; set; }
        public string mesto_raboti { get; set; }
        public string ceh_otdel { get; set; }
        public string doljnost { get; set; }
        public string telefon_rabochii { get; set; }
        public string semeinoe_polojenie { get; set; }
        public string nomer_vb { get; set; }
        public string data_vidachi_vb { get; set; }
        public string kategoruya_godnosti { get; set; }
        public string komissariat { get; set; }
        public string kategoriya_zapasa { get; set; }
        public string voinskoe_zvanie { get; set; }
        public string kod_VUS { get; set; }
        public string sostav_profil { get; set; }
        public string voinskii_uchet { get; set; }
        public string chto_zakonchil { get; set; }
        public string kogda_zakonchil { get; set; }
        public string nacionalnost { get; set; }
        public string pol { get; set; }
        public string data_change { get; set; }
        public string dokument_ob_obrazov { get; set; }
        public string serial_dokumenta { get; set; }
        public string number_dokumenta { get; set; }
        public string data_reg_po_mj { get; set; }
        public string sem_polojenie_OKIN { get; set; }
        public string kod_OKATO { get; set; }
        public string kod_OKIN_grajd { get; set; }
        public string kod_OKIN_inyaz { get; set; }
        public string staj { get; set; }
        public string kod1 { get; set; }
        public string data_zapoln_anketi { get; set; }
    }
}
