//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoMySql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int id_man { get; set; }
        public string number_zach { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> kod_platelshik { get; set; }
        public string god_postup { get; set; }
        public Nullable<int> otchislen_iz_group { get; set; }
        public string number_kontrakta { get; set; }
        public string kod1 { get; set; }
        public string data_change { get; set; }
    }
}
