namespace Starikov
open System.Dynamic
type AboutUserModel () =
    member val Surname : string = null with get, set
    member val Name : string = null with get, set
    member val Patron : string = null with get, set
    member val INN : string = null with get, set
    member val SPasp : string = null with get, set
    member val NPasp : string = null with get, set
    member val WhoGiveP : string = null with get, set
    member val BirthDate : string = null with get, set
    member val BirthPlace : string = null with get, set
    member val Strana : string = null with get, set
    member val Region : string = null with get, set
    member val Index : string = null with get, set
    member val City : string = null with get, set
type MessageToGroupModel () =
    member val id_group = Unchecked.defaultof<int> with get, set
    member val message_subject = Unchecked.defaultof<string> with get, set
    member val message_body = Unchecked.defaultof<string> with get, set
type MessageToStudentModel () =
    member val id_student = Unchecked.defaultof<int> with get, set
    member val message_subject = Unchecked.defaultof<string> with get, set
    member val message_body = Unchecked.defaultof<string> with get, set
type Anceta () =
    member val lastname = Unchecked.defaultof<string> with get, set
    member val name = Unchecked.defaultof<string> with get, set
    member val patron = Unchecked.defaultof<string> with get, set
    member val group = Unchecked.defaultof<string> with get, set
    member val birthdate = Unchecked.defaultof<string> with get, set
    member val grajdanstvo = Unchecked.defaultof<string> with get, set
    member val voinskii_uchet = Unchecked.defaultof<string> with get, set
    member val education = Unchecked.defaultof<string> with get, set
    member val family_status = Unchecked.defaultof<string> with get, set
    member val Childrens = Unchecked.defaultof<string> with get, set
    member val pasport_serial = Unchecked.defaultof<string> with get, set
    member val pasport_number = Unchecked.defaultof<string> with get, set
    member val pasport_date = Unchecked.defaultof<string> with get, set
    member val pasport_getter = Unchecked.defaultof<string> with get, set
    member val pasport_code = Unchecked.defaultof<string> with get, set
    member val inn = Unchecked.defaultof<string> with get, set
    member val PFRF = Unchecked.defaultof<string> with get, set
    member val pIndex = Unchecked.defaultof<string> with get, set
    member val pRegion = Unchecked.defaultof<string> with get, set
    member val pCity = Unchecked.defaultof<string> with get, set
    member val pDistrict = Unchecked.defaultof<string> with get, set
    member val pStreet = Unchecked.defaultof<string> with get, set
    member val pHome = Unchecked.defaultof<string> with get, set
    member val pRoom = Unchecked.defaultof<string> with get, set
    member val fIndex = Unchecked.defaultof<string> with get, set
    member val fRegion = Unchecked.defaultof<string> with get, set
    member val fCity = Unchecked.defaultof<string> with get, set
    member val fDistrict = Unchecked.defaultof<string> with get, set
    member val fStreet = Unchecked.defaultof<string> with get, set
    member val fHome = Unchecked.defaultof<string> with get, set
    member val fRoom = Unchecked.defaultof<string> with get, set
    member val d_tel = Unchecked.defaultof<string> with get, set
    member val m_tel = Unchecked.defaultof<string> with get, set
    member val alter_lang = Unchecked.defaultof<string> with get, set
    member val Bonuses = Unchecked.defaultof<string> with get, set
    member val educationType = Unchecked.defaultof<string> with get, set
    member val dealNumber = Unchecked.defaultof<string> with get, set
    member val dealStartDate = Unchecked.defaultof<string> with get, set
    member val whoPay = Unchecked.defaultof<string> with get, set
    member val pastSport = Unchecked.defaultof<string> with get, set
    member val presantSport = Unchecked.defaultof<string> with get, set
    member val futureSport = Unchecked.defaultof<string> with get, set
    member val motherContact = Unchecked.defaultof<string> with get, set
    member val fatherContact = Unchecked.defaultof<string> with get, set    